### ISSUE TITLE
Regenerate Superuser password doesn't work

### ISSUE THREAD

**Issue by kranack** [dieonar/MyMumb-Panel#12]
Je viens de remarquer que chez moi, le bouton pour regénérer le mot de passe du superuser ne marche pas.

Je n'ai pas d'erreurs dans les logs de PHP, la page se recharge juste et le mot de passe reste inchangé.

**Comment by dieonar** [comment]
Je vais regarder ça, Merci.

**Comment by dieonar** [comment]
Le problème a été reglé.

**Comment by kranack** [comment]
Cool, merci :-)
