### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by invisan** [dieonar/MyMumb-Panel#14]
When i try to login i only get the message Unable to connect, Please check your login information.
Login Info and Server are correct though. This happens if i use the specified login or if i try with the settings set to false. 

Ice Secret in the config and the Server are the same.

Im Using Ice-3.5.1 on Ubuntu 14.04 Trusty.

This is what my /var/log/apache2/error.log looks like. 

[Tue Aug 04 22:21:01.812697 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineClass() expects exactly 8 parameters, 6 given in /var/www/mumblewi/inc/Murmur.php on line 591, referer: http://localhost/mumblewi/?login
[Tue Aug 04 22:21:01.812755 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineProxy() expects parameter 1 to be object, null given in /var/www/mumblewi/inc/Murmur.php on line 593, referer: http://localhost/mumblewi/?login
[Tue Aug 04 22:21:01.812774 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineException() expects exactly 5 parameters, 4 given in /var/www/mumblewi/inc/Murmur.php on line 616, referer: http://localhost/mumblewi/?login
[Tue Aug 04 22:21:01.812788 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineException() expects exactly 5 parameters, 4 given in /var/www/mumblewi/inc/Murmur.php on line 640, referer: http://localhost/mumblewi/?login
[Tue Aug 04 22:21:01.812801 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineException() expects exactly 5 parameters, 4 given in /var/www/mumblewi/inc/Murmur.php on line 664, referer: http://localhost/mumblewi/?login
[Tue Aug 04 22:21:01.812815 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineException() expects exactly 5 parameters, 4 given in /var/www/mumblewi/inc/Murmur.php on line 688, referer: http://localhost/mumblewi/?login
[Tue Aug 04 22:21:01.812828 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineException() expects exactly 5 parameters, 4 given in /var/www/mumblewi/inc/Murmur.php on line 712, referer: http://localhost/mumblewi/?login
[Tue Aug 04 22:21:01.812841 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineException() expects exactly 5 parameters, 4 given in /var/www/mumblewi/inc/Murmur.php on line 736, referer: http://localhost/mumblewi/?login
.............
[Tue Aug 04 22:21:01.813188 2015] [:error] [pid 10886] [client 127.0.0.1:47569] PHP Warning:  IcePHP_defineOperation() expects exactly 9 parameters, 8 given in /var/www/mumblewi/inc/Murmur.php on line 1211, referer: http://localhost/mumblewi/?login

**Comment by dieonar** [comment]
did you use "icesecretread=" in your murmur config ini?

**Comment by invisan** [comment]
No its not set.

Config looks like this.

# Murmur configuration file.
#
# General notes:
# * Settings in this file are default settings and many of them can be overridden
#   with virtual server specific configuration via the Ice or DBus interface.
# * Due to the way this configuration file is read some rules have to be
#   followed when specifying variable values (as in variable = value):
#     * Make sure to quote the value when using commas in strings or passwords.
#        NOT variable = super,secret BUT variable = "super,secret"
#     * Make sure to escape special characters like '\' or '"' correctly
#        NOT variable = """ BUT variable = "\""
#        NOT regex = \w* BUT regex = \\w*

# Path to database. If blank, will search for
# murmur.sqlite in default locations or create it if not found.
database=/var/lib/mumble-server/mumble-server.sqlite

# If you wish to use something other than SQLite, you'll need to set the name
# of the database above, and also uncomment the below.
# Sticking with SQLite is strongly recommended, as it's the most well tested
# and by far the fastest solution.
#
#dbDriver=QMYSQL
#dbUsername=
#dbPassword=
#dbHost=
#dbPort=
#dbPrefix=murmur_
#dbOpts=

# Murmur defaults to not using D-Bus. If you wish to use dbus, which is one of the
# RPC methods available in Murmur, please specify so here.
#
dbus=system

# Alternate D-Bus service name. Only use if you are running distinct
# murmurd processes connected to the same D-Bus daemon.
#dbusservice=net.sourceforge.mumble.murmur

# If you want to use ZeroC Ice to communicate with Murmur, you need
# to specify the endpoint to use. Since there is no authentication
# with ICE, you should only use it if you trust all the users who have
# shell access to your machine.
# Please see the ICE documentation on how to specify endpoints.
ice="tcp -h 127.0.0.1 -p 6502"

# Ice primarily uses local sockets. This means anyone who has a
# user account on your machine can connect to the Ice services.
# You can set a plaintext "secret" on the Ice connection, and
# any script attempting to access must then have this secret
# (as context with name "secret").
# Access is split in read (look only) and write (modify) 
# operations. Write access always includes read access,
# unless read is explicitly denied (see note below).
#
# Note that if this is uncommented and with empty content,
# access will be denied.

#icesecretread=
icesecretwrite=justachangepassword

# How many login attempts do we tolerate from one IP
# inside a given timeframe before we ban the connection?
# Note that this is global (shared between all virtual servers), and that
# it counts both successfull and unsuccessfull connection attempts.
# Set either Attempts or Timeframe to 0 to disable.
#autobanAttempts = 10
#autobanTimeframe = 120
#autobanTime = 300

# Specifies the file Murmur should log to. By default, Murmur
# logs to the file 'murmur.log'. If you leave this field blank
# on Unix-like systems, Murmur will force itself into foreground
# mode which logs to the console.
logfile=/var/log/mumble-server/mumble-server.log

# If set, Murmur will write its process ID to this file
# when running in daemon mode (when the -fg flag is not
# specified on the command line). Only available on
# Unix-like systems.
pidfile=/var/run/mumble-server/mumble-server.pid

# The below will be used as defaults for new configured servers.
# If you're just running one server (the default), it's easier to
# configure it here than through D-Bus or Ice.
#
# Welcome message sent to clients when they connect.
welcometext="<br />Enjoy your stay!<br />"

# Port to bind TCP and UDP sockets to.
port=64738

# Specific IP or hostname to bind to.
# If this is left blank (default), Murmur will bind to all available addresses.
#host=

# Password to join server.
serverpassword=

# Maximum bandwidth (in bits per second) clients are allowed
# to send speech at.
bandwidth=72000

# Maximum number of concurrent clients allowed.
users=100

# Amount of users with Opus support needed to force Opus usage, in percent.
# 0 = Always enable Opus, 100 = enable Opus if it's supported by all clients.
#opusthreshold=100

# Maximum depth of channel nesting. Note that some databases like MySQL using
# InnoDB will fail when operating on deeply nested channels.
#channelnestinglimit=10

# Regular expression used to validate channel names.
# (Note that you have to escape backslashes with \ )
#channelname=[ \\-=\\w\\#\\[\\]\\{\\}\\(\\)\\@\\|]+

# Regular expression used to validate user names.
# (Note that you have to escape backslashes with \ )
#username=[-=\\w\\[\\]\\{\\}\\(\\)\\@\\|\\.]+

# Maximum length of text messages in characters. 0 for no limit.
#textmessagelength=5000

# Maximum length of text messages in characters, with image data. 0 for no limit.
#imagemessagelength=131072

# Allow clients to use HTML in messages, user comments and channel descriptions?
#allowhtml=true

# Murmur retains the per-server log entries in an internal database which
# allows it to be accessed over D-Bus/ICE.
# How many days should such entries be kept?
# Set to 0 to keep forever, or -1 to disable logging to the DB.
#logdays=31

# To enable public server registration, the serverpassword must be blank, and
# this must all be filled out.
# The password here is used to create a registry for the server name; subsequent
# updates will need the same password. Don't lose your password.
# The URL is your own website, and only set the registerHostname for static IP
# addresses.
# Only uncomment the 'registerName' parameter if you wish to give your "Root" channel a custom name.
#
registerName=Just a Server
#registerPassword=secret
#registerUrl=http://mumble.sourceforge.net/
#registerHostname=

# If this option is enabled, the server will announce its presence via the 
# bonjour service discovery protocol. To change the name announced by bonjour
# adjust the registerName variable.
# See http://developer.apple.com/networking/bonjour/index.html for more information
# about bonjour.
#bonjour=True

# If you have a proper SSL certificate, you can provide the filenames here.
# Otherwise, Murmur will create it's own certificate automatically.
#sslCert=
#sslKey=

# If Murmur is started as root, which user should it switch to?
# This option is ignored if Murmur isn't started with root privileges.
uname=mumble-server

# If this options is enabled, only clients which have a certificate are allowed
# to connect.
#certrequired=False

# If enabled, clients are sent information about the servers version and operating
# system.
#sendversion=True

# You can configure any of the configuration options for Ice here. We recommend
# leave the defaults as they are.
# Please note that this section has to be last in the configuration file.
#
[Ice]
Ice.Warn.UnknownProperties=1
Ice.MessageSizeMax=65536

**Comment by dieonar** [comment]
Yeah, it's a good point, I will do changes this weekend

**Comment by invisan** [comment]
No need to already did it. Will upload it later today when im back home. 
One thing i couldnt do which would be quite usefull is the ability to change the Port of the Server later on.

**Comment by invisan** [comment]
My Fork is updated now. If you want to merge it with yours go ahead and look at the changes and see if its working out for you :-) Im also working on a more detailed overview for the Servers currently. X/Y Slots in Use as an example.

**Comment by dieonar** [comment]
Yeah, thanks i will give a look this weekend, thanks anyways ;)
