### ISSUE TITLE
Nginx

### ISSUE THREAD

**Issue by Lickwid** [dieonar/MyMumb-Panel#15]
Has anyone gotten this working with nginx?  I'm running ispconfig3 and was trying to set it up.  Added this to the nginx options:

```
   location /mumble {
       proxy_pass http://127.0.0.1:6502;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
   }
```

I get "No data recieved" when I go to the website, and accourding to the mumble logs the server is up. Not able to connect though.

**Comment by dieonar** [comment]
When i've tested nginx with the panel, i didn't edit the nginx options like that.

The first thing that comes to mind when i look your configuration :
By default the murmur ice service is on the port 6502, and you trying to put webservice on it, try to change the port by something else.
