### ISSUE TITLE
Cannot authenticate

### ISSUE THREAD

**Issue by hplodur** [dieonar/MyMumb-Panel#18]
Hi,

It seems that I cannot authenticate. I have followed your instructions and did everything that you have listed. I have tried with all Murmur.php files (version 3.4.2, 3.5.1 and generated by me) still no luck. I have tried to authenticated with icesecret and SuperUser and password without any luck.

The strange thing is that with self-generated Murmur.php I get no errors in apache error_log but with one that you ship I get the following messages:

PHP Warning:  IcePHP_defineClass() expects exactly 8 parameters, 6 given
PHP Warning:  IcePHP_defineException() expects exactly 5 parameters, 4 given

I only get the above with version 3.4.2. For version 3.5.1 and the generated by me 3.6.3 I get no errors.

There are not logs in murmur.log as well as in apache error_log.

Could you please let me know how can I debug this to find the cause. To see if it's actually communicating with ICE (that is up and running).

Thank you very much in advance.

**Comment by dieonar** [comment]
I will check it out soon as possible

**Comment by dieonar** [comment]
Can you tell me on which OS are you?

**Comment by hplodur** [comment]
CentOS 7.
I have installed zeroc-ice-php version 3.5.1 but still cannot connect. I'm trying any other panel to be sure that it's not a problem with your application but the OS or system owner (me).

**Comment by hplodur** [comment]
After switching to Debain 8 and replacing Murmur.php version 3.4.2 with 3.5.1 everything is working as expected. I think the problem is with CentOS 7 and zeroc php package.

**Comment by hplodur** [comment]
By the way the panel is beautiful!

**Comment by dieonar** [comment]
Thanks mate :)
I will work on a fix for CentOS when i will have the time
