### ISSUE TITLE
Logs out After Creating New Mumble Server

### ISSUE THREAD

**Issue by MPTMG** [dieonar/MyMumb-Panel#19]
Functionally everything works with creating a new mumble server through the web interface. However, after creating a new mumble server it automatically logs me out of web interface and I must log back in to continue.

After I log back in everything was executed correctly and the new mumble server exists with the appropriate options. Tested with Safari and Firefox.

Any ideas as to what is causing the automatic logout?

**Comment by dieonar** [comment]
It's now fixed !
