### ISSUE TITLE
Replace md5 with something secure

### ISSUE THREAD

**Issue by Lartza** [dieonar/MyMumb-Panel#6]
If you want a hashed password for security, md5 and sha1 are as good as plaintext.

Not to say that it's a bad thing since many config files have passwords like this as plaintext but then you could just remove the md5 alltogether.

**Comment by dieonar** [comment]
Mmmh, Yeah why not. Thanks for the suggestions, i will probably do this when i will ge more time ;)

**Comment by Lartza** [comment]
Why close this without resolution?

**Comment by dieonar** [comment]
i have opened a new branch, Thoses changes have been already made, and i will push it when i will be back on my pc.
